#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare -r BASH_COMPLETION_PATH="$(brew --prefix 2> /dev/null)/share/bash-completion/bash_completion"

if [ -f "$BASH_COMPLETION_PATH" ]; then

    # Use the latest `bash-completion`.

    . "$BASH_COMPLETION_PATH"

    # Make Bash complete the `g` alias just like it does `git`.

    complete -o default -o nospace -F _git g

fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Docker copletions

declare -r DOCKER_COMPLETION_PATH="$(brew --prefix 2> /dev/null)/etc/bash_completion.d/docker"

if [ -f "$DOCKER_COMPLETION_PATH" ]; then

    # Load Docker completions

    . "$DOCKER_COMPLETION_PATH"

fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Git completions

declare -r GIT_COMPLETION_PATH="$(brew --prefix 2> /dev/null)/etc/bash_completion.d/git-completion.bash"

if [ -f "$GIT_COMPLETION_PATH" ]; then

    # Load Git completions

    . "$GIT_COMPLETION_PATH"

fi

